name: Amalgamate Ubuntu CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Compile with amalgamation
        run: |
          mkdir build &&
          mkdir build/fast_float &&
          python3 ./script/amalgamate.py > build/fast_float/fast_float.h &&
          cp tests/string_test.cpp build/ &&
          cd build &&
          g++ -Werror=old-style-cast string_test.cpp
